# This file is part of the meta-pitrac layer
BBPATH .= ":${LAYERDIR}"

# We have a conf and classes directory, append to BBPATH
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "pitrac"
BBFILE_PATTERN_pitrac := "^${LAYERDIR}/"
BBFILE_PRIORITY_pitrac = "10"

LAYERSERIALS_COMPAT_pitrac = "scarthgap"
LAYERDEPENDS_pitrac = "core raspberrypi"
LAYERSERIES_COMPAT_pitrac = "scarthgap"

# Recommended for u-boot support for raspberrypi5
LAYERRECOMMENDS_pitrac = "lts-u-boot-mixin"