require conf/distro/poky.conf

DISTRO = "pitrac"
DISTRO_NAME = "PiTrac Distro"
SDK_VENDOR = "-pitracsdk"
TARGET_VENDOR = "-pitrac"

DISTRO_FEATURES:append = " pam libpam nfs usrmerge systemd"

# Enable systemd support
VIRTUAL_RUNTIME_dev_manager = "systemd"
VIRTUAL_RUNTIME_init_manager = "systemd"
VIRTUAL_RUNTIME_initscript = ""
VIRTUAL_RUNTIME_syslog = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

LICENSE_FLAGS_ACCEPTED:append = " synaptics-killswitch commercial"

ENABLE_SPI_BUS = "1"
ENABLE_I2C = "1"
RASPBERRYPI_CAMERA_V2 = "1"
RASPBERRYPI_CAMERA_V3 = "1"
ENABLE_UART = "1"

